language: go
go:
- 1.13.x
- 1.14.x
script:
- export GO111MODULE=on
- "./pre-commit"
- GOOS=darwin GOARCH=amd64 go build -o build/operator-sdk-manager-${TRAVIS_TAG}-x86_64-apple-darwin
- GOOS=linux   GOARCH=amd64 go build -o build/operator-sdk-manager-${TRAVIS_TAG}-x86_64-linux-gnu
before_deploy:
- zip operator-sdk-manager-${TRAVIS_TAG}-x86_64-apple-darwin.zip operator-sdk-manager-${TRAVIS_TAG}-x86_64-apple-darwin
  README.md
- zip operator-sdk-manager-${TRAVIS_TAG}-x86_64-linux-gnu.zip operator-sdk-manager-${TRAVIS_TAG}-x86_64-linux-gnu
  README.md
- sha256sum *zip > SHASUMS256.txt
deploy:
  provider: releases
  api_key: U3dPEyXsH/i4/HTkgdf1rCnVPWCn6zhbOs3r1COURDd1Q6GjNzF9/dNYDthDy25hyMZLi5WEkwQZyieoAGFSqOK8+XhIMpwZ7m2V2Yg0FiYNDdcwZwcyzoUAVA0+SfYdy6tBX5PvWJHgBqCACaKSeEQksKN/OFo2TAmk5eGHUxQwZ4maTbhcx5p8iSCT95byj507IBp1JxTudLLH10NIcu90wy4s++jpDNo1VkAsr4Y2XYGd+L4u81CBsmC6For3XpDnjc2sKpizKmyYIK11e8KlpmfkMyfONufsfrQ+JWrqlg+3VRteSOU66i1AgZrG+IQ0QtCDxPOKmUDvTziGOI+8ZMwGAwLtd1gvn5tsWakWHUlIL912KGar4NM/psZi9MvfNZWBpVs5cvnQZkULSkClCxOnn4b44T2wVGgVS4WWUnJSUxGJQHP5XP+uxwxjL0b087rFlNiAU4W1cGYAuRq5ZsLq4GWBcKSm7cIeASyml2a+e2U5MTGZTWJEVKisKci6WmAN9Gty/N7Bm13fE1RWGqGGOptd2bmb205zlxMuwlOFbRsD9dlOnED+tIHOpavb6+nAzCCJqM438ZytsT+gpbGY1PrOp/i9sHcnOD2xFLey28E+cRRnAVaggDheSfQD6RGzI1ncddc2dpmsHCa02urGdgoBt5Bc3soKJ6A=
  file:
  - operator-sdk-manager-${TRAVIS_TAG}-x86_64-apple-darwin.zip
  - operator-sdk-manager-${TRAVIS_TAG}-x86_64-linux-gnu.zip
  - SHASUMS256.txt
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: U3dPEyXsH/i4/HTkgdf1rCnVPWCn6zhbOs3r1COURDd1Q6GjNzF9/dNYDthDy25hyMZLi5WEkwQZyieoAGFSqOK8+XhIMpwZ7m2V2Yg0FiYNDdcwZwcyzoUAVA0+SfYdy6tBX5PvWJHgBqCACaKSeEQksKN/OFo2TAmk5eGHUxQwZ4maTbhcx5p8iSCT95byj507IBp1JxTudLLH10NIcu90wy4s++jpDNo1VkAsr4Y2XYGd+L4u81CBsmC6For3XpDnjc2sKpizKmyYIK11e8KlpmfkMyfONufsfrQ+JWrqlg+3VRteSOU66i1AgZrG+IQ0QtCDxPOKmUDvTziGOI+8ZMwGAwLtd1gvn5tsWakWHUlIL912KGar4NM/psZi9MvfNZWBpVs5cvnQZkULSkClCxOnn4b44T2wVGgVS4WWUnJSUxGJQHP5XP+uxwxjL0b087rFlNiAU4W1cGYAuRq5ZsLq4GWBcKSm7cIeASyml2a+e2U5MTGZTWJEVKisKci6WmAN9Gty/N7Bm13fE1RWGqGGOptd2bmb205zlxMuwlOFbRsD9dlOnED+tIHOpavb6+nAzCCJqM438ZytsT+gpbGY1PrOp/i9sHcnOD2xFLey28E+cRRnAVaggDheSfQD6RGzI1ncddc2dpmsHCa02urGdgoBt5Bc3soKJ6A=
