language: go
go:
- 1.14.x
script:
- export GO111MODULE=on
- GOOS=darwin GOARCH=amd64 go build -o build/operator-sdk-manager-x86_64-apple-darwin
- GOOS=linux GOARCH=amd64 go build -o build/operator-sdk-manager-x86_64-linux-gnu
deploy:
  provider: releases
  api_key:
    secure: umGE+vPumJ7vjYhZuCoH0bmTG07+qULon7TGsChqM93J1YOsGr4swb2Xzz+QqugxDVfFrrbCQFpOIHesqGvDLHmiapPRMl/TiREB53fLWA57tIShr51BSJ+fT9XP+0mHndlzmETdkJ3VgUeuQ4vJTcF2CwP+7lnkP8IWTzniY6uRLHloYWKnjTGSpm5MXothhC2gJS/Y7wdP87nbIoUHSEPJz0VURN4rrmmc7ishxJXR1bSwTTJnoR/7p3j93sYZOIJvwtOND9fk8y5ihv3IeeQOgIOXT48J7UXgPAJR6ypN1UbJRL+7CEnsaa5WnfX6/a+HWQ/8963taZ4UnRTm8/Ekr021wm6v1mkWpGm4tpIQNWemp1NXr7nJ3A1lszrJMQU5f+2KQuYSgeQmrSxE2Oq31oB68cGdjLQ+/Ubqay3r8jNAeltcmfhgWcgkWjT6M30ya+QWoFitSHUdUl5w3pcIUAggcIl+k6FtZOmq5dqZ4emHC1nNFfXOJa6jgKQRa5sMWDoV03e6A4FOR9XAPF55lQ7M7DFQ5HuONDWbvnBLLxocYvL5W8Z/eXSxA0zi7vlmcu/s8zriNNC5vNUsC3Lz6NMkr8hRwvYaYDGzmPPX5WK5FGZMBTlod9GuJgn+KAu9oY5EQx+RpoSKBCyVPHqWsz5Nx+MGJQyjco5o43U=
  file:
    - operator-sdk-manager-x86_64-apple-darwin
    - operator-sdk-manager-x86_64-linux-gnu
  on:
    repo: akoserwal/operator-sdk-manager
  skip_cleanup: 'true'
  tags: true
env:
  global:
    secure: U3dPEyXsH/i4/HTkgdf1rCnVPWCn6zhbOs3r1COURDd1Q6GjNzF9/dNYDthDy25hyMZLi5WEkwQZyieoAGFSqOK8+XhIMpwZ7m2V2Yg0FiYNDdcwZwcyzoUAVA0+SfYdy6tBX5PvWJHgBqCACaKSeEQksKN/OFo2TAmk5eGHUxQwZ4maTbhcx5p8iSCT95byj507IBp1JxTudLLH10NIcu90wy4s++jpDNo1VkAsr4Y2XYGd+L4u81CBsmC6For3XpDnjc2sKpizKmyYIK11e8KlpmfkMyfONufsfrQ+JWrqlg+3VRteSOU66i1AgZrG+IQ0QtCDxPOKmUDvTziGOI+8ZMwGAwLtd1gvn5tsWakWHUlIL912KGar4NM/psZi9MvfNZWBpVs5cvnQZkULSkClCxOnn4b44T2wVGgVS4WWUnJSUxGJQHP5XP+uxwxjL0b087rFlNiAU4W1cGYAuRq5ZsLq4GWBcKSm7cIeASyml2a+e2U5MTGZTWJEVKisKci6WmAN9Gty/N7Bm13fE1RWGqGGOptd2bmb205zlxMuwlOFbRsD9dlOnED+tIHOpavb6+nAzCCJqM438ZytsT+gpbGY1PrOp/i9sHcnOD2xFLey28E+cRRnAVaggDheSfQD6RGzI1ncddc2dpmsHCa02urGdgoBt5Bc3soKJ6A=
